
[build]
  command = "npm run build:netlify"
  publish = ".next"
  [functions]
    directory = ".next/server"

[context.production.environment]
  NEXT_PUBLIC_IGNORE_BUILD_ERRORS = "true"
  NODE_OPTIONS = "--openssl-legacy-provider"