[build]
  command = "bash build.sh || true"
  publish = ".next"
  [functions]
    directory = ".next/server"

[context.production.environment]
  NEXT_PUBLIC_IGNORE_BUILD_ERRORS = "true"
  NODE_OPTIONS = "--openssl-legacy-provider"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "false"